### ISSUE TITLE
Provide Ontop Docker image for ARM64 architecture (Apple M1)

### ISSUE THREAD

**Issue by fracorco** [ontop/ontop#532]
Ontop images on [Docker Hub](https://hub.docker.com/r/ontop/ontop-endpoint/tags) are currently only available for the architecture `linux/amd64`. Therefore, they need to be run using QEMU emulation on ARM machines like Apple M1 (but I understand there are also cloud offers that run on ARM).

Besides being inefficient, some Ontop features may not work in QEMU emulation, such as the automatic restarting of Ontop when a change in one of the configuration files is detected (as *"filesystem change notification APIs (inotify) do not work under qemu emulation."*, see [here](https://docs.docker.com/desktop/mac/apple-silicon/)).

Now the [`openjdk:11-jre-buster`](https://hub.docker.com/layers/openjdk/library/openjdk/11.0.6-jre-buster/images/sha256-353ab5edbfae2597e7f25b3650696735f0ba6277d7e1e73881c71a0fcf36a7d8?context=explore) base image used by Ontop is already available for `linux/arm64/v8`, and if the Ontop Docker image is build on an ARM machine (an Apple M1), an Ontop Docker image for architecture `linux/arm64/v8` is generated that does not require QEMU emulation with its associated drawbacks (tested, works).

I propose to also provide `linux/arm64/v8` Docker images of Ontop on Docker Hub, so to avoid the need for ARM users to build Ontop by themselves. In principle, docker images for different architectures can be generated from a single machine (assuming QEMU emulation is available to run the build) using [`docker buildx`](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images), e.g.,
```
docker buildx create --use
docker buildx build --platform linux/amd64,linux/arm64 .
```

If not providing an ARM image, I suggest that the Ontop documentation (esp. the one on Docker Hub) should explicitly document this issue and provide users with instructions for building a `linux/arm64/v8` image. To that respect but also more in general, the current Dockerfile and `build-image.sh` script compile Ontop using the JDK installed on the user machine, so availability of a suitable JDK is required (vs. JRE alone) and, due to differences in installed JDK or possibly previously aborted build attempts, reproducibility is not as good as the one achievable using a two stage build where the Maven Docker image is used in a 'builder' stage to compile Ontop within a controlled Docker environment (e.g., with given versions of JDK, Maven, etc).

Should you decide to follow this suggestion, I may support with implementing the required changes.

**Comment by ghxiao** [comment]
@fracorco I have already encountered the issue "filesystem change notification APIs (inotify) do not work under qemu emulation." on my new Macbook Pro. 

I think the best way to this problem is to use buildx to create images for multiple platforms, as you suggested, and upload them to Docker Hub.

It is great that you want to implement this feature.

**Comment by fracorco** [comment]
@ghxiao @bcogrel Branch [multiplatform-docker-image](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image) contains an updated Docker setup supporting building a multiplatform (`linux/amd64` + `linux/arm64`) Ontop image. It features modified `build-image.sh` script and `Dockerfile` and a new `Dockerfile.dockerignore` file;  `build/distribution/pom.xml` was also slightly modified.

With the new setup:
- [`docker buildx`](https://docs.docker.com/engine/reference/commandline/buildx/) is being used to support generating a multi-platform image. It comes bundled with Docker, so it's mostly a matter of calling [`docker buildx build`](https://docs.docker.com/engine/reference/commandline/buildx_build/) instead of `docker build` (or call [`docker buildx install`](https://docs.docker.com/engine/reference/commandline/buildx_install/) once to configure it as replacement of `docker build`, until [`docker buildx uninstall`](https://docs.docker.com/engine/reference/commandline/buildx_uninstall/) is executed).
- A *multi-stage* [Dockerfile](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/Dockerfile) is used that allows either building the Ontop image from pre-built binaries compiled outside Docker as it has worked so far (build passing option `--target image-from-binaries`), or building from sources within Docker, using a `compile` stage that leverages a Dockerized maven image (default option, corresponding to stage `image-from-sources`). This allows users to build Ontop without having a suitable JDK and Maven on their machine, obtaining consistent results as JDK and Maven versions are controlled by the Dockerfile. For instance, the following command, to be run from Ontop root folder, generates and tags the Ontop image for the local platform (which may be amd64 or arm64):
  ```
  docker buildx build --load -t ontop/ontop-endpoint:5.0.0-SNAPSHOT -f client/docker/Dockerfile .
  ```
  Note that building from sources this way is slow (at least for one time builds that could not benefit from caching, which I configured). The main reason is that the dockerized Maven has to download all plugins and dependencies, and this takes a lot of time.
- Script [`build-image.sh`](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/build-image.sh), as before, supports building from binaries compiled outside Docker, integrating with the usual Maven build workflow (i.e., reuse Maven cache, reuse already-compiled Maven artifacts) and thus requiring a JDK being installed. The script has been updated as follows:
    - It automatically extracts the Ontop version (to use as image tag) from the main `pom.xml`, allowing however to override it (as well as the image name) via script command line options
    - It supports cross-compiling to generate a multi-platform Docker image for both `linux/amd64` and `linux/arm64` (option `-x`). Note that Docker limitations basically require such image to be pushed to a repository, as it cannot be stored locally (precisely, outside the buildx cache). Therefore, when cross-compiling the script also pushes the image to a Docker repository, which can be configured by changing the image name
    - As before, it supports generating a Docker image for the current platform, in which case pushing it is optional (has to be enabled via option `-p`)
- As a minor optimization, when building the Docker image (either via the script or directly from Dockerfile), the `ontop-cli` assembly is built but not needlessly zipped, this way avoiding unzipping it during the Docker build. This was implemented by adding (to [`build/distribution/pom.xml`](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/build/distribution/pom.xml#L130)) the support for system property `assembly.cli.format` that indicates if/how to package the `ontop-cli` artifacts.
- As a minor optimization, a [`Dockerfile.dockerignore`](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/Dockerfile.dockerignore) file has been added side-by-side with the `Dockerfile` (where it is automatically picked up by Docker), in order to reduce the size of the Docker *context* that is copied to the `compile` stage during build (by excluding directories `.git` and `target`, context size is reduced from hundreds of MBs to ~75MB)

A multi-platform Docker image built with the new setup has been loaded on a separate throwaway Docker hub [repository](https://hub.docker.com/repository/docker/fracorco/ontop-test/tags?page=1&ordering=last_updated), and can be used by pulling `fracorco/ontop-test:5.0.0-SNAPSHOT` in place of `ontop/ontop-endpoint:VERSION`.

Next steps:
- please validate the `linux/arm64` image built with the new setup in an ARM environment (e.g., an Apple M1 machine), possibly using the prebuilt image at `fracorco/ontop-test:5.0.0-SNAPSHOT`
- please consider that the JRE Docker image currently used by ontop has been [deprecated](https://hub.docker.com/_/openjdk/). The new setup still use that image (for both JRE and also indirectly in the Maven `compile` stage), but it's advised to switch to another image. [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin) images appear to be good candidates, and may also allow reducing the size of Ontop image. In particular, remaining on a JRE 11, there are
  - [eclipse-temurin:11-jre-ubi9-minimal](https://hub.docker.com/layers/library/eclipse-temurin/11-jre-ubi9-minimal/images/sha256-4e4c74aba3c781be4374cec62c28d7ac4d4cc6598863ae71bcddcc6029bb6155?context=explore) - tested, works, slightly increases Ontop image size from 346M to 352M. 
  - [eclipse-temurin:11-jre-alpine](https://hub.docker.com/layers/library/eclipse-temurin/11-jre-alpine/images/sha256-c99492a6cf649269c2e39f468fa64dacca233e362059ce1deb218c56e51969a0?context=explore) - tested, does not work as it misses `bash` (need to adapt the `entrypoint.sh` script), reduces Ontop image size from 346M to 207M.

**Comment by ghxiao** [comment]
Hi @fracorco 

Thanks for the great work.

> * please validate the `linux/arm64` image built with the new setup in an ARM environment (e.g., an Apple M1 machine), possibly using the prebuilt image at `fracorco/ontop-test:5.0.0-SNAPSHOT`

I have tried to build the image on my machine (with Apple M1) and use your prebuilt image. 
Both work flawlessly with https://github.com/ontopic-vkg/destination-tutorial.

Please go ahead with other steps.

**Comment by ghxiao** [comment]
I have a problem with the new build-image script. Not sure if this is Mac-specific.

```
$ ./build-image.sh
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

**Comment by fracorco** [comment]
Hi @ghxiao, @bcogrel,  

the `grep`-related issue is Mac-specific and should have been fixed by using `sed` in place of `grep` in the affected command. Please try it again and see if it works also on Mac.

Additional changes:
* The `entrypoint.sh` has been reworked as follows:
  - it now requires just a plain `sh` POSIX shell, for compatibility with lightweight images missing `bash` like Alpine Linux ones (that was the idea, but the current image still has `bash` available, so this capability is not used)
  - for boolean environment variables (e.g., `ONTOP_DEV_MODE`), the script checks that the variable value is *not* set to `false`, in which case the variable is ignored (this permits setting such variables in `docker-compose.yml` by delegating to values set in `.env`)
  - if the script is called with arguments, these arguments specify the Ontop command to run (`endpoint` if omitted) and its options, to which other options are added as usual based on supplied `ONTOP_` environment variables. For instance, try running `docker run -it --rm ontop/ontop-endpoint:5.0.0-SNAPSHOT help` (rationale: this allows accessing all features of Ontop via a single Docker image, and not just its endpoint)
  - new environment variables `ONTOP_WAIT_FOR` (e.g., set to `db:5432`) and `ONTOP_WAIT_TIMEOUT` (e.g., `300` seconds, default is unlimited) allow waiting for the availability of zero or more TCP ports, this way embedding the functionality of scripts like `wait-for-it.sh`
* The base Docker image is now [eclipse-temurin:11-jre-focal](https://hub.docker.com/layers/library/eclipse-temurin/11-jre-focal/images/sha256-6d27bb5052c9b5d8c2bf0cb5e36a698c20588664c2b9ca7b000d15737b546462?context=explore) (i.e., an Ubuntu 20.04 LTS) and has been matched to [maven:3-eclipse-temurin-11-focal](https://hub.docker.com/layers/library/maven/3-eclipse-temurin-11-focal/images/sha256-a5e797701468300f761cb8b4bf726b7f233c2d816a94ba45be6328579ca42719?context=explore) for the compile stage. Remarks:
  - the size of the resulting Ontop Docker image is 306M and it's hard to do better since we cannot use Alpine Linux that lacks the support for platform `linux/arm64` (however, it runs on `linux/amd64` with an image size of 209M);
  - an alternative base image would be [eclipse-temurin:11-jre-ubi9-minimal](https://hub.docker.com/layers/library/eclipse-temurin/11-jre-ubi9-minimal/images/sha256-4e4c74aba3c781be4374cec62c28d7ac4d4cc6598863ae71bcddcc6029bb6155?context=explore) that is a stripped-down RHEL image with emphasis on security (fast updates) and reliability, but support and usage terms when used as a free Docker image would need to be carefully checked;
  - we need to apt-install the `nc` tool (`netcat` package) to reliably support scripts like `wait-for-it.sh` and the port waiting functionality in our `entrypoint.sh` script (note that there is no alternative base image having `netcat` installed);
  - **the `apt-get` commands run when cross-compiling may result in `ERROR: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c apt-get update` ..." did not complete successfully: exit code: 100`** if QEMU is not properly setup with arm64 emulation support. This can be achieved:
    - on Linux by installing package `qemu-user-static`  (e.g., `sudo apt install qemu-user-static` on Debian/Ubuntu)
    - alternatively, this support can be installed via Docker via `docker run -it --rm --privileged tonistiigi/binfmt --install all` (not tried, not sure what it changes on the host system)

The text images [fracorco/ontop-test](https://hub.docker.com/repository/docker/fracorco/ontop-test) have been updated and can be used for testing. Still have to update the documentation (waiting for new features to be discussed and finalized).

**Note: QEMU-related errors may be bypassed by not running `apt-get` commands and therefore dropping `nc` and `wait-for-it.sh` support (we may implement port waiting in `entrypoint.sh` using something else, but existing Ontop applications using `wait-for-it.sh` will be broken).**

**Note: due to the capability of running arbitrary Ontop command (not just `endpoint`) you may want to consider changing the image name to simply `ontop`, instead of `ontop-endpoint`**

**Comment by fracorco** [comment]
Another aspect to consider is whether to configure [Docker healthchecks](https://docs.docker.com/engine/reference/builder/#healthcheck) to let Docker monitor the status of an Ontop container by executing a periodic healthcheck command, and report in case that command repeatedly fails for a certain number of times leading the container to be labeled as *unhealthy*.

The command can be `wget` or `curl` sending a probe SPARQL query and returning success (exit code 0) if the query is successfully answered. We can make the query configurable by the user, and a default lightweight query could be:
```sparql
SELECT * {}
```
which translates to
```sql
SELECT 1 AS uselessVariable
FROM ( SELECT 1 ) tdummy
```
basically just checking that the Ontop connectioction to the DB is alive (note: Ontop does run this query and will fail if the DB cannot be queried).
The healthcheck command using `wget` (available in our base images) could be:
```bash
wget -q -t1 --spider "http://localhost:8080/sparql?query=${ONTOP_HEALTHCHECK_QUERY:-SELECT * { \}}" || exit 1
```

Remarks:
* Docker reports the healthcheck results through its API and monitoring tools can use it, such as [Nagios](https://exchange.nagios.org/directory/Plugins/Software/Check-Docker/details)
* Docker Swarm is said to support restart of unhealthy services, while such functionality for plain Docker / Docker Compose is packaged in a [autoheal](https://hub.docker.com/r/willfarrell/autoheal) container; not sure Ontop would benefit from being restarted if the DB is not reachable, though (as this won't solve the issue)
* running healthcheck queries is not transparent to users, as they cause accesses to Ontop and the DB and leave traces in the logs, hence it seems better not to enable this mechanism out of the box but let the users opt-in in case
* the healthcheck mechanism may be configured in the Dockerfile, in which case it will be enabled for each container instantiated from the Ontop image if not explicitly disabled by users, or enabled/disabled via the [`docker run`](https://docs.docker.com/engine/reference/run/#healthcheck) command or the [`docker-compose.yml`](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck) file

Summing up and unless the decision is to enable automatically this healthcheck mechanism (in the Dockerfile), I think it's better to leave it out and include in the documentations instructions about how to enable it via `docker run` or `docker-compose.yml`.

**Comment by fracorco** [comment]
@ghxiao, @bcogrel: Further revision of Docker setup in branch [multiplatform-docker-image](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image), feedback is required.

Summary of changes so far w.r.t. Ontop 4.2.2 (see also partially updated [README](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image/client/docker)):
- **Support for linux/amd64 and linux/arm64 platforms** with a multi-platform image, using a multi-stage dockerfile and a revised `build-image.sh` script (option `-x`) based on [`docker buildx`](https://docs.docker.com/engine/reference/commandline/buildx/) and supporting compiling Ontop inside the Docker build.
- **Rootless image** with Ontop run by an unprivileged [`ontop` user](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/Dockerfile#L53) and all image files owned by `root` (i.e., unmodifiable, more safe), although this can be overridden by users via `docker run` [`--user`](https://docs.docker.com/engine/reference/run/#user) argument or `docker compose` [`user`](https://docs.docker.com/compose/compose-file/#user) directive.
- **Support for any ontop-cli command** and not just the `endpoint` one, which remains the default if no command line arguments are supplied to `entrypoint.sh` when starting the Ontop container.
- **Extended log configuration** that allows setting the logback configuration file (via `ONTOP_LOG_CONFIG`) and root log level (`ONTOP_LOG_LEVEL`), and enable tracing of entrypoint commands (`ONTOP_LOG_ENTRYPOINT`); see [README](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image/client/docker#logging-debugging-jmx-and-jvm-tuning).
- **JMX configuration** on port 8686 via new boolean flag `ONTOP_CONFIGURE_JMX`; this port may then be exposed on the host (similarly to port 8080) to allow monitoring and debugging (esp. w.r.t. threading and memory issues) the Ontop process via JMX clients such as [visualvm](https://visualvm.github.io/), see [README](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image/client/docker#logging-debugging-jmx-and-jvm-tuning).
- **Docker healthchecks** enabled by default with either *process* state, *port* (default) or *query*-based checking strategy, see [README](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image/client/docker#docker-healthchecks).
- **Waiting for DBMS port availability** [implemented](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/entrypoint.sh#L188) directly in Ontop `entrypoint.sh` script without need for external scripts such as `wait-for-it.sh`, see [README](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image/client/docker#lazy-or-delayed-initialization).
- **Added OCI standard labels** to generated image, via [dockerfile](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/Dockerfile#L44) (for static information) and [build-image.sh](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/build-image.sh#L44) script (for version and build timestamp).
- **Using custom JRE (via jlink)** in [dockerfile](https://github.com/ontop/ontop/blob/feature/multiplatform-docker-image/client/docker/Dockerfile#L20) to reduce image size (from 300M to 184M uncompressed, from 130M to 104M compressed), as per [Eclipse Temurin suggestions](https://hub.docker.com/_/eclipse-temurin).
- **Various polishing** including more robust handling of boolean flags and interplay of environment variables, configuration defaults and `ONTOP_JAVA_ARGS` extra settings in the `entrypoint.sh` script.

Next steps:
- **Feedback required** on changes and new features.
- **Improve documentation** in the [website](https://ontop-vkg.org/dev/new-release.html#update-docker-hub) and in the [README](https://github.com/ontop/ontop/tree/feature/multiplatform-docker-image/client/docker):
  - provide instructions to users and developers about the different ways to build the Ontop Docker image, as listed above;
  - provide instructions about how to run other Ontop CLI commands, e.g., via `docker run` examples that show how to deal with mounting volumes for input/output files.
- **Cleanup logback configuration files**. The following 3 configuration files end up in the `ontop-cli.zip` and (originally) in the Docker image, whereas only `/log/logback.xml` is actually needed and the other files should be removed to avoid confusion by users (e.g., editing the wrong file and being puzzled it has no effects):
  - file `/logback.xml` in the root directory appear not to be used;
  - file `/log/logback.xml` is used by the `ontop` script of `ontop-cli.zip`, and also by the Docker image;
  - file `/log/logback-debug.xml` was used by the Docker image to set `DEBUG` as root log level, but this is now achieved using the same `/log/logback.xml` and having an environment variable `ONTOP_LOG_LEVEL` select the log level (note: file appenders have been also commented out to avoid creating the log file even if disabled).
- **Improve `ontop` startup script in `ontop-cli` (optional)**: some (or all) of the functionalities implemented in `entrypoint.sh` can be actually moved to the `ontop` script in `ontop-cli`, so that users running Ontop natively may also benefit from them.

**Comment by fracorco** [comment]
(adding @tirrolo to the discussion)

We noticed that command line arguments `--db-metadata` and `--constraint`, which allow passing additional DB-related metadata/constraints, are *not* supported by Ontop CLI command `boostrap`, although they may appear relevant to it. These arguments are instead supported by Ontop CLI commands `endpoint`, `materialize`, `query` and `validate`.

**Additional details**. Arguments `--db-metadata` and `--constraint` are defined in [`OntopMappingOntologyRelatedCommand`](https://github.com/ontop/ontop/blob/version5/client/cli/src/main/java/it/unibz/inf/ontop/cli/OntopMappingOntologyRelatedCommand.java#L26) which is not inherited - and cannot be inherited, due to definition of ontology and mapping-related arguments - by class [`OntopBoostrap`](https://github.com/ontop/ontop/blob/version5/client/cli/src/main/java/it/unibz/inf/ontop/cli/OntopBootstrap.java) implementing command `bootstrap`. The values supplied for these arguments can then be injected via [`OntopMappingSQLAllConfiguration.Builder`](https://github.com/ontop/ontop/blob/0e1324d980c588b8dfc26bf2ef281265c84f3f63/mapping/sql/all/src/main/java/it/unibz/inf/ontop/injection/OntopMappingSQLAllConfiguration.java#L22) which is inherited by the `OntopSQLOWLAPIConfiguration.Builder` already used by the `bootstrap` command implementation, so their support may be straightforward. If and when addressing this issue, please consider also command `extract-db-metadata` implemented by [`OntopExtractDBMetadata`](https://github.com/ontop/ontop/blob/version5/client/cli/src/main/java/it/unibz/inf/ontop/cli/OntopExtractDBMetadata.java), which accepts only argument `--properties` but maybe should accept as well DB-related arguments like `--constraint`, `--db-metadata` (to be merged with extracted one?) and the ones defined in [`OntopAbstractCommand`](https://github.com/ontop/ontop/blob/version5/client/cli/src/main/java/it/unibz/inf/ontop/cli/AbstractOntopCommand.java) (e.g., `--db-user`).

**Comment by bcogrel** [comment]
Hi @fracorco, thanks a lot for your proposal!
I tried it on Linux with different existing projects and it worked fine, well done!

The changes looks to me, I think we can merge the branch.  @ghxiao, do you agree with this?

We still need to rename all occurrences of "Ontop views" by "lenses", but this can be done after merging.
As for the next steps, we can do them after merging (no need to wait).

**Comment by bcogrel** [comment]
I renamed Ontop views as lenses (#582). Could you please update the new script of the Docker image?

Here is the change in the current script: https://github.com/ontop/ontop/blob/version5/client/docker/entrypoint.sh#L86

The CLI parameter is now `--lenses`.

**Comment by fracorco** [comment]
> [...] Could you please update the new script of the Docker image? [...]

Done by integrating `version5` changes to `entrypoint.sh` and `README.md` into the new versions of these files.

**Comment by ghxiao** [comment]
Hi @fracorco @bcogrel  when testing the latest commit, I got a problem:

I have tried to run ./build-image.sh in the root directory and in `client/docker/` directory, with and without the `-x` option. Do you experience a similar problem?

<img width="935" alt="Screenshot 2022-12-26 at 11 00 34" src="https://user-images.githubusercontent.com/1907371/209535748-9401c488-ef18-40b4-86cd-f7c78fc8a397.png">

**Comment by fracorco** [comment]
> [...] I got a problem:
> 
> I have tried to run ./build-image.sh in the root directory and in `client/docker/` directory, with and without the `-x` option. Do you experience a similar problem?
> [...]

I did some testing and I could not reproduce the issue (I'm on Linux). For extra safety, I just switched from `build/distribution/target/ontop` to `build/distribution/target/ontop-docker` as the location where the content of the Ontop docker image is assembled (when compiling Ontop locally, i.e., when not passing option `-C` that compiles Ontop within Docker). However, I don't expect this minor change to solve the issue.

Could you please try the following?
1. before pulling new changes, report also the output of `ls -l build/distribution/target` to complement the screenshot;
2. pull my latest changes, try again running `build-image.sh` without parameters, and report error message along with output of `ls -l build/distribution/target`;
3. (unrelated to the issue but for completeness) try running `build-image.sh -C` and see if it works and the built image `ontop/ontop-endpoint:5.0.0-SNAPSHOT` appears when running `docker image ls -a`.

Thanks in advance!

**Comment by ghxiao** [comment]
Hi, I have followed your steps. The problem persists with `build-image.sh`, but `build-image.sh -C` seems working. See details below:

> Could you please try the following?
> 
> 1. before pulling new changes, report also the output of `ls -l build/distribution/target` to complement the screenshot;

<img width="1140" alt="Screenshot 2022-12-26 at 19 59 27" src="https://user-images.githubusercontent.com/1907371/209579275-caeff0a0-b864-4442-8edf-0d7ae3918a58.png">

> 2. pull my latest changes, try again running `build-image.sh` without parameters, and report error message along with output of `ls -l build/distribution/target`;

<img width="1140" alt="Screenshot 2022-12-26 at 20 21 53" src="https://user-images.githubusercontent.com/1907371/209579293-d00b0db1-cae9-4ef2-ae3b-1dec6277f4e7.png">

> 3. (unrelated to the issue but for completeness) try running `build-image.sh -C` and see if it works and the built image `ontop/ontop-endpoint:5.0.0-SNAPSHOT` appears when running `docker image ls -a`.

<img width="1166" alt="Screenshot 2022-12-26 at 20 46 20" src="https://user-images.githubusercontent.com/1907371/209579424-19d0f29a-ed38-41f1-aaf3-615945cf8a81.png">

**Comment by fracorco** [comment]
@ghxiao: Thanks for the feedback. The presence of `ontop-cli-5.0.0-SNAPSHOT.zip` under `build/distribution/target` (resulting from some previous compiling of Ontop) was confusing the script `build-image.sh`, which wrongly expected only a directory to match pattern `ontop-cli-*` (where `*` matches the version/suffix, so not to hard-code it in the script). Fixed by ensuring the pattern do match only a directory. Please try again running `./client/docker/build-image.sh`: it should work now.

**Comment by ghxiao** [comment]
@fracorco Perfect. I was suspecting like that and now it works! The branch is merged.
